let messe_fisse = [
    { "diocesi_id": "001", "chiesa_id": "0005", "paese": "Costigliole Saluzzo", "chiesa_nome": "S. Maria Maddalena", "prefes": "PRE", "ora": "18:00", "note": "In estate a Ceretto" },
    { "diocesi_id": "001", "chiesa_id": "0005", "paese": "Costigliole Saluzzo", "chiesa_nome": "S. Maria Maddalena", "prefes": "FES", "ora": "11:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0006", "paese": "Costigliole Saluzzo", "chiesa_nome": "Confraternita", "data": "05/02/2023", "prefes": "FES", "ora": "18:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0011", "paese": "Piasco", "chiesa_nome": "S. Giovanni", "prefes": "PRE", "ora": "17:00", "note": "Il 1° e 3° Sabato del mese" },
    { "diocesi_id": "001", "chiesa_id": "0011", "paese": "Piasco", "chiesa_nome": "S. Giovanni", "prefes": "FES", "ora": "10:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0012", "paese": "Piasco", "chiesa_nome": "S. Antonio", "prefes": "PRE", "ora": "17:00", "note": "Il 2° e 4° Sabato del mese" },
    { "diocesi_id": "001", "chiesa_id": "0012", "paese": "Piasco", "chiesa_nome": "S. Antonio", "prefes": "FES", "ora": "11:00", "note": "La 1^ e la 3^ Domenica del mese" },
    { "diocesi_id": "001", "chiesa_id": "0012", "paese": "Piasco", "chiesa_nome": "S. Antonio", "prefes": "FES", "ora": "18:00", "note": "" },    
    { "diocesi_id": "001", "chiesa_id": "0013", "paese": "Piasco", "chiesa_nome": "Mad. del Carmine", "prefes": "FES", "ora": "08:30", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0016", "paese": "Rossana", "chiesa_nome": "Maria V. Assunta", "prefes": "PRE", "ora": "18:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0016", "paese": "Rossana", "chiesa_nome": "Maria V. Assunta", "prefes": "FES", "ora": "11:00", "note": "La 2^ e la 4^ Domenica del mese" },
    { "diocesi_id": "001", "chiesa_id": "0017", "paese": "Rossana", "chiesa_nome": "Mad. delle Grazie", "prefes": "PRE", "ora": "15:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0018", "paese": "Rossana", "chiesa_nome": "S. Marco", "prefes": "FES", "ora": "09:30", "note": "La 1^ e la 3^ Domenica del mese" },
	
    { "diocesi_id": "001", "chiesa_id": "0027", "paese": "Verzuolo", "chiesa_nome": "S. Bartolomeo", "prefes": "PRE", "ora": "18:30", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0027", "paese": "Verzuolo", "chiesa_nome": "S. Bartolomeo", "prefes": "FES", "ora": "10:00", "note": "" },	
    { "diocesi_id": "001", "chiesa_id": "0028", "paese": "Verzuolo", "chiesa_nome": "S. Andrea", "prefes": "PRE", "ora": "18:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0028", "paese": "Verzuolo", "chiesa_nome": "S. Andrea", "prefes": "FES", "ora": "11:15", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0029", "paese": "Verzuolo", "chiesa_nome": "S. Maria della Scala", "prefes": "FES", "ora": "09:00", "note": "" },	
    { "diocesi_id": "001", "chiesa_id": "0030", "paese": "Verzuolo", "chiesa_nome": "SS. Filippo e Giacomo", "prefes": "PRE", "ora": "18:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0030", "paese": "Verzuolo", "chiesa_nome": "SS. Filippo e Giacomo", "prefes": "FES", "ora": "10:00", "note": "" },
    { "diocesi_id": "001", "chiesa_id": "0030", "paese": "Verzuolo", "chiesa_nome": "SS. Filippo e Giacomo", "prefes": "FES", "ora": "20:30", "note": "" },	
	
	{ "diocesi_id": "001", "chiesa_id": "0003", "paese": "Brossasco", "chiesa_nome": "S. Andrea", "prefes": "PRE", "ora": "18:30", "note": "Nel periodo estivo potrebbe non esserci o essere ad altri orari (collegata a Valmala)" },	
	{ "diocesi_id": "001", "chiesa_id": "0003", "paese": "Brossasco", "chiesa_nome": "S. Andrea", "prefes": "FES", "ora": "10:30", "note": "Nel periodo estivo potrebbe non esserci o essere ad altri orari (collegata a Valmala)" },	
	
	{ "diocesi_id": "001", "chiesa_id": "0009", "paese": "Manta", "chiesa_nome": "S. Maria degli Angeli", "prefes": "PRE", "ora": "18:30", "note": "Nel periodo estivo potrebbe non esserci o essere ad altri orari (collegata a Valmala)" },	
	{ "diocesi_id": "001", "chiesa_id": "0009", "paese": "Manta", "chiesa_nome": "S. Maria degli Angeli", "prefes": "FES", "ora": "10:30", "note": "Nel periodo estivo potrebbe non esserci o essere ad altri orari (collegata a Valmala)" },	
	{ "diocesi_id": "001", "chiesa_id": "0009", "paese": "Manta", "chiesa_nome": "S. Maria degli Angeli", "prefes": "FES", "ora": "10:30", "note": "Nel periodo estivo potrebbe non esserci o essere ad altri orari (collegata a Valmala)" },	
]